### ISSUE TITLE
ReferenceError localStorage is not defined in NextJS

### ISSUE THREAD

**Issue by Mitsunee** [nanostores/persistent#2]
Error:
```
ReferenceError: localStorage is not defined
    at eval (webpack-internal:///./node_modules/@nanostores/persistent/index.js:23:1)
    at Object../node_modules/@nanostores/persistent/index.js (/home/mitsunee/work/REDACTED/.next/server/pages/index.js:561:1)
    at __webpack_require__ (/home/mitsunee/work/REDACTED/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./lib/stores/appStore.js:11:80)
    at Object../lib/stores/appStore.js (/home/mitsunee/work/REDACTED/.next/server/pages/index.js:275:1)
    at __webpack_require__ (/home/mitsunee/work/REDACTED/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:18:75)
    at Object../pages/index.js (/home/mitsunee/work/REDACTED/.next/server/pages/index.js:550:1)
    at __webpack_require__ (/home/mitsunee/work/REDACTED/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/home/mitsunee/work/REDACTED/.next/server/pages/index.js:1072:52)
``` 

Steps to reproduce:  
I tried to port an existing store in a NextJS app to persistent like:

```js
import { getValue } from "nanostores";
import { createPersistentStore } from "@nanostores/persistent";

export const appStore = createPersistentStore("appUser", {
  name: "",
  email: "",
  // other redacted values here, one of which being an array|null, rest booleans
});
```

I suspect the fix I contributed in the main repo in past is causing this. If I recall correctly I used something like `if (localStorage)`, when it should have been `if (typeof localStorage !== undefined)` (that's what I usually do with `window` in useEffects now to prevent similar errors)

**Comment by ai** [comment]
Fixed 78d6e4e

**Comment by Mitsunee** [comment]
it's still not quite working for me yet, I'm getting `"[object Object]"` in localStorage now:

![image](https://user-images.githubusercontent.com/19474909/129190206-a09c7b64-b6a0-4de3-974f-0e60a057e9a0.png)

(the store ending in "User" is the one similar to my example above)

**Comment by ai** [comment]
You need to use `createPersistentMap` for key-value values

**Comment by ai** [comment]
I improved typing to avoid this mistake 069bdee
